name: Laravel Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  web-dev-sync:
  name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Use PHP 8.3
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'

    - name: ğŸ”¨ Build NPM (1)
      run: |
        npm install

    - name: ğŸ”¨ Build Composer (2)
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    
    - name: ğŸ”‘ Generate Laravel Key
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

    - name: ğŸ’¾ Give Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: ğŸ™ Copy .env.cpanel to .env
      run: php -r "file_exists('.env') || copy('.env.cpanel', '.env');"

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.kodemaya.my.id
        username: admin-dev@kodemaya.my.id
        password: KodeMayaBangkit#321
        protocol: ftp
        port: 21
        exclude: |
          **/.git*
